apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: hello-arc
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
    kubernetes.io/elb.subnet-id: 2f1bb458-8e52-471f-86aa-431c4facb2df
    kubernetes.io/elb.autocreate: '{"type":"public","bandwidth_name":"cce-bandwidth-hello_arc_elb","bandwidth_chargemode":"bandwidth","bandwidth_size":10,"bandwidth_sharetype":"PER","eip_type":"5_bgp","name":"cce_hello_arc_elb"}'
spec:
  interval: 1m
  releaseName: nginx-ingress
  chart:
    spec:
      chart: ./hello-arc/charts/nginx-ingress
  values:
    controller:
      image:
        repository: k8s.gcr.io/ingress-nginx/controller
        tag: "v1.1.1"
      replicaCount: 3
